FROM python:2
LABEL maintainer="Rajesh"

ENV PYTHONUNBUFFERED 1
ENV PATH="/scripts:${PATH}"
RUN apt-get update
#RUN apt-get install -y libxml2-dev libxslt1-dev antiword poppler-utils
RUN pip install --upgrade pip

COPY ./requirements.txt ./requirements.txt

RUN pip install -r ./requirements.txt

RUN mkdir /notejam
WORKDIR /notejam
COPY ./notejam /notejam
COPY ./scripts /scripts
RUN chmod +x /scripts/*
CMD ["entrypoint.sh"]
